// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCziX521VaLI-PJdHRAlihnRT3kO0bOJ6Y',
    appId: '1:975747675605:web:f6bc7598abb2966d14395c',
    messagingSenderId: '975747675605',
    projectId: 'business-management-3d18f',
    authDomain: 'business-management-3d18f.firebaseapp.com',
    storageBucket: 'business-management-3d18f.appspot.com',
    measurementId: 'G-WQTD8T6011',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Ts2OQxW16eVRUc6Las5lz9-pCcGwOzw',
    appId: '1:975747675605:android:0055cd9439ca718914395c',
    messagingSenderId: '975747675605',
    projectId: 'business-management-3d18f',
    storageBucket: 'business-management-3d18f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2l4xHpBGoiJIvJijbc3dA0yFRUQwHo4M',
    appId: '1:975747675605:ios:c919d56891849dc314395c',
    messagingSenderId: '975747675605',
    projectId: 'business-management-3d18f',
    storageBucket: 'business-management-3d18f.appspot.com',
    iosBundleId: 'com.example.gas',
  );
}
